### ISSUE TITLE
Dependency injection doesn't work

### ISSUE THREAD

**Issue by zxdstyle** [go-mojito/mojito#3]
![image](https://user-images.githubusercontent.com/38398954/178137231-db2c7144-859e-490c-a85a-09ea6605075d.png)

**Comment by nilathedragon** [comment]
Thank you very much for your report!
I was able to reproduce the issue with the screenshot provided and a fix has been merged into main.

I also tagged a release v0.0.9 which includes the fix and some other small changes!
