### ISSUE TITLE
[Bug]: websocket.Context.Closed() undefined

### ISSUE THREAD

**Issue by rlsvr** [go-mojito/mojito#56]
### Description

 go run main.go
# command-line-arguments
./main.go:9:11: ctx.Closed undefined (type "github.com/go-mojito/mojito/websocket".Context has no field or method Closed)

### How to Reproduce

1. Run the code snippet

### Expected Behavior

Able to compile.

### Version

0.0.16

### Code Snippet

```go
package main

import "github.com/go-mojito/mojito"
import websocket "github.com/go-mojito/mojito/websocket"

func SomeHandler(ctx websocket.Context) {
    for !ctx.Closed() {
        var msg string
        ctx.Receive(&msg)
        ctx.Send(msg)
    }
}

func main() {
  mojito.GET("/", func(ctx mojito.Context) {
    ctx.String("Hello World")
  })
  mojito.GET("/ws", SomeHandler)
  mojito.ListenAndServe(":8123")
}
```

### Checklist:

- [X] I agree to follow Mojito's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by nilathedragon** [comment]
I have created a new release `v0.0.17` which contains the fix

**Comment by rlsvr** [comment]
Thank you!
