### ISSUE TITLE
[Bug]: High Allocation count when using fields in logging

### ISSUE THREAD

**Issue by nilathedragon** [go-mojito/mojito#92]
### Description

The logging system is causing a lot of allocations related to fields even when using a zero-allocation logging backend like zerolog.

https://github.com/go-mojito/mojito/blob/cab236e346064194081441bc6696edc9a551ab77/pkg/logger/util.go#L7-L12

### How to Reproduce

Use fields when logging

### Expected Behavior

When using a zero-allocation logging backend I'd expect to not be allocating.

### Version

master

### Checklist:

- [X] I agree to follow Mojito's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by 0SkillAllLuck** [comment]
Probably a good idea to let the implementation of a log decide how to handle Fields.

In case of zerolog it should maybe not even use Fields but acutally use the zerolog methods

**Comment by nilathedragon** [comment]
Yeah moving closer to implementation should fix this. Then we can benefit from zero-alloc. and still provide DI for loggers.

**Comment by 0SkillAllLuck** [comment]
We also still do allocations if the log level is below what is configured as the check is only done on the last `.Info` or whatever level you use call.
Maybe we should switch the order to make select the level earlier something like:

```
// Old way 
logger.Field("foo", "bar").Debug("My debug message");

// New way
logger.AsDebug().Field("foo", "bar").Msg("My debug message");
```

Alternatively if we want to make it breaking but a bit easier in the future:

```
logger.Debug().Field("foo", "bar").Msg("My debug message");
```

**Comment by nilathedragon** [comment]
The breaking way seems better ngl.

**Comment by nilathedragon** [comment]
We switched the Logger interface to match slog.Logger
